spring:
  application:
    name: cbmm-system

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

logging:
  level:
    org.springframework: DEBUG
    org.example: DEBUG

